[tool.poetry]
name = "asttrs"
version = "0.5.3"
description = "A attrs-style wrapper for python ast"
authors = ["ryanchao2012 <ryanchao2012@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ryanchao2012/asttrs"



[tool.poetry.dependencies]
python = "^3.7"
attrs = "<22.0.0"
cattrs = "<2.0.0"
astor = "<1.0.0"
black = "<23.0.0"
isort = "<6.0.0"

[tool.poetry.dev-dependencies]
ipython = "^7.28.0"
flake8 = "^3.9.2"
pytest-cov = "^3.0.0"
pytest = "^7.0.1"
invoke = "^1.7.0"
coverage = "^6.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
